version: '3.8'

# Simplified Windows-specific Docker Compose configuration
services:
  codex:
    build:
      context: .
      dockerfile: Dockerfile.windows
    container_name: codex-cli
    volumes:
      - .:/workspace:rw
      - codex-data:/root/.codex
    working_dir: /workspace
    environment:
      - CODEX_SANDBOX=docker
    stdin_open: true
    tty: true
    network_mode: bridge

volumes:
  codex-data:
    name: codex-data
