version: '3.8'

# Windows-specific Docker Compose configuration with simplified paths
services:
  codex:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codex-cli
    volumes:
      # Using simplified volume mounting for Windows compatibility
      - .:/workspace:rw
      - codex-data:/root/.codex
    working_dir: /workspace
    env_file:
      - ./.env
    environment:
      - CODEX_SANDBOX=docker
    stdin_open: true
    tty: true
    # Use bridge network mode for Windows compatibility
    network_mode: bridge
    entrypoint: ["dotenv", "--", "codex"]
    command: []

volumes:
  codex-data:
    name: codex-data
